### ISSUE TITLE
Tendency - CoreOracle#getTokenValue Returns an Incorrect USD Value Due to Precision Loss

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-blueberry-judging#18]
Tendency

high

# CoreOracle#getTokenValue Returns an Incorrect USD Value Due to Precision Loss

## Summary
`getTokenValue` function in [CoreOracle.sol](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L151), will return the wrong USD value for some tokens
## Vulnerability Detail
When a user calls [openPositionFarm](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/spell/AuraSpell.sol#L63-L147) in any of the spell contracts in order to add liquidity into a pool, [BasicSpell#_validateMaxLTV](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/spell/BasicSpell.sol#L185) is called to validate if the current position Loan-to-Value ratio is at `maxLTV`. [_validateMaxLTV](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/spell/BasicSpell.sol#L185) function then makes a call to two more functions, [getDebtValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L422) and [getIsolatedCollateralValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L433), in order to get the position debt value and the isolated collateral value respectively, the both functions further make calls to [CoreOracle.getTokenValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L151) to get the USD value of the total debt of the position and to get the USD value of the isolated collateral of the given position respectively.

The getTokenValue function, further makes the following inner calls 
getTokenValue  --> [_getTokenValue ](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L123)--> [_getPrice](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L70) --> Oracle

The problem here, is with the precision factor returned from the oracle and the calculation here:
```solidity
    function _getTokenValue(
        address token,
        uint256 amount
    ) internal view returns (uint256 value) {
        uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
        value = (_getPrice(token) * amount) / 10 ** decimals; //@audit wrongly divides by token decimal here
    } 
```

Here is the `getPrice` function:
```solidity
   /// @notice Return USD price of given token, multiplied by 10**18.
    /// @param token The ERC-20 token to get the price of.
    function getPrice(address token) external view override returns (uint256) {
        return _getPrice(token);
    }
```
Here is a comment from the Blueberry team: 

 @dev `SoftVault` is communicating with `bTokens` to lend and borrow underlying tokens from/to Blueberry Money Market.
       Underlying tokens can be ERC20 tokens listed by Blueberry team, such as USDC, USDT, DAI, WETH, ...

The comment suggests that the underlying token can be a `6` decimal precision token like USDC and USDT.

looking at the `_getTokenValue` value calculation, if the ERC20 token is a token with `6` decimal precision, the wrong value will be returned, due to a precision loss.
Here is an example calculation, to show the impact of this issue when the underlying token is USDT:

if token price = 1 * 10** 18
         amount =  10, 000
       decimals = 6

Using, Value = (price * amount) / 10** decimals
                     = (1 * 10** 18 * 10, 000) / 10** 6
                     = 10,000,000,000,000,000 or 1 * 10** 16

But if, token price = 1 * 10** 18
                amount =  10, 000
               decimals = 18

Value = (price * amount) / 10** decimals
           = (1 * 10** 18 * 10, 000) / 10** 18
           = 10,000

The `getTokenValue` function, returns the wrong USDT value due to a precision loss. With this, the [_validateMaxLTV](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/spell/BasicSpell.sol#L185) check will always pass, since the user will appear to have more isolated collateral than he has (when the the isolated collateral token has `6` decimal precision), and will always revert (when the debt token has `6` decimal precision)

## Impact
users with six decimal precision collateral token, will still be able to open a position even with a bad LTV ratio
## Code Snippet
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L70
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L151
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/spell/BasicSpell.sol#L185
## Tool used

Manual Review

## Recommendation
The base oracle contract gets and returns price from any of the supported oracles, this oracles returns the price multiplied by 10**18, in order to get the USD value, I will recommend, dividing by the same precision instead

```solidity
 function _getTokenValue(
        address token,
        uint256 amount
    ) internal view returns (uint256 value) {
        uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
      -  value = (_getPrice(token) * amount) / 10 ** decimals;
      + value = (_getPrice(token) * amount) / 10 ** 18;
    }

```

**Comment by Tendency001** [comment]
Escalate for 10 USD
I think this issue wasn't rightly judged, I have shown every step on how the precision loss is possible, the comments in specifically softvault suggests that tokens like USDT can be the underlying token, this token price are returned with an 18 decimal precision from the Oracle, checking the token decimal, using
 ```solidity
uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
``` 
will return the token decimal which is 6, multiplying the returned value with this decimal will not result in the right price value, this will directly affect the _validateMaxLTV function. 
I will appreciate if this issue is looked into, I believe it is an issue that must be fixed

**Comment by sherlock-admin** [comment]
> Escalate for 10 USD
> I think this issue wasn't rightly judged, I have shown every step on how the precision loss is possible, the comments in specifically softvault suggests that tokens like USDT can be the underlying token, this token price are returned with an 18 decimal precision from the Oracle, checking the token decimal, using
>  ```solidity
> uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
> ``` 
> will return the token decimal which is 6, multiplying the returned value with this decimal will not result in the right price value, this will directly affect the _validateMaxLTV function. 
> I will appreciate if this issue is looked into, I believe it is an issue that must be fixed

You've deleted an escalation for this issue.

**Comment by IAm0x52** [comment]
The code is functioning as intended. It always normalizes the value to 18 dp. The price returned by the oracle is the price of 1 unit of the token.

```
Using, Value = (price * amount) / 10** decimals
= (1 * 10** 18 * 10, 000) / 10** 6
= 10,000,000,000,000,000 or 1 * 10** 16

But if, token price = 1 * 10** 18
amount = 10, 000
decimals = 18

Value = (price * amount) / 10** decimals
= (1 * 10** 18 * 10, 000) / 10** 18
= 10,000
```

Watson points out the above math as incorrect but that is the correct math.

**Comment by Tendency001** [comment]
Yes, I have carefully studied all of the oracles in Blueberry, all of the oracles always normalize and returns the price in 18 dp, 

the problem is in how `_getTokenValue` handles the returned price whenever it is called, `getTokenValue` is supposed to return the USD equivalent of the price, it tries to achieve this by dividing the price by the returned precision in order to get the value 
```solidity
    function _getTokenValue(
        address token,
        uint256 amount
    ) internal view returns (uint256 value) {
        uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
        value = (_getPrice(token) * amount) / 10 ** decimals;
    }
```
Now the problem is, it does this by dividing by the dp of the underlying token, which in my argument, when the underlying token is of the 6 dp tokens like USDT then the problem occurs(will be dividing 18dp / 6dp), the price will still be left with a 1e12 precision

I will also add, 
all of the functions take this returned value to be the USD value of the requested price

[getDebtValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L422)
```solidity
debtValue = oracle.getTokenValue(pos.debtToken, debt);
```
[getIsolatedCollateralValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L433)

```solidity
        icollValue = oracle.getTokenValue(
            pos.underlyingToken,
            underlyingAmount
        );
```

**Comment by IAm0x52** [comment]
No because the token is already denominated in it's native decimals. We're not dividing 18 dp / 6dp we are dividing 24 (18 + 6) dp / 6 dp. If you divide by 1e18 as you suggest then you would the value would always be normalized to the token dp rather than 18 dp like it should be

**Comment by Tendency001** [comment]
You are missing something, since this issue directly relates to the other, please check out my response over #19

the dp of the token is canceled out and the price is returned in only 18 dp, it's in the code, i didn't write it

please confirm for yourself:
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/ChainlinkAdapterOracle.sol#L77-L97
