### ISSUE TITLE
Tendency - Positions With 6 Decimal Precision Underlying Tokens Will be Wrongly Flagged as Liquidatable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-blueberry-judging#19]
Tendency

high

# Positions With 6 Decimal Precision Underlying Tokens Will be Wrongly Flagged as Liquidatable

## Summary
Wrong value calculation in [CoreOracle._getTokenValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L151) will result in the return of the wrong USD value for tokens with six decimal precision, which can wrongly get users position liquidated
## Vulnerability Detail
In BlueBerryBank contract, to check if a position is liquidatable or not, this is checked:
```solidity
    function isLiquidatable(uint256 positionId) public view returns (bool) {
        return
            getPositionRisk(positionId) >=
            banks[positions[positionId].underlyingToken].liqThreshold;
    }
```
The [getPositionRisk](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L456) function calls the following functions, [getPositionValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L392), [getDebtValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L422), [getIsolatedCollateralValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L433), using the return value of this functions for computation

```solidity
   function getPositionRisk(
        uint256 positionId
    ) public view returns (uint256 risk) {
        uint256 pv = getPositionValue(positionId);
        uint256 ov = getDebtValue(positionId);
        uint256 cv = getIsolatedCollateralValue(positionId);

        if (
            (cv == 0 && pv == 0 && ov == 0) || pv >= ov // Closed position or Overcollateralized position
        ) {
            risk = 0;
        } else if (cv == 0) {
            // Sth bad happened to isolated underlying token
            risk = Constants.DENOMINATOR;
        } else {
            risk = ((ov - pv) * Constants.DENOMINATOR) / cv; 
        }
    }
```
The called functions, return a USD equivalent value by interacting with [oracle.getTokenValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L151).

`CoreOracle.geTokenValue` further makes this calls [_getTokenValue](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L123) --> [_getPrice](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L70) -->Oracle

The `_getPrice` function, gets and returns the price of the token from the oracle with an 18 decimal precision
```solidity
  /// @notice Return USD price of given token, multiplied by 10**18.
    /// @param token The ERC-20 token to get the price of.
    function _getPrice( //@audit price will be multiplied by 18 here
        address token
    ) internal view whenNotPaused returns (uint256) {
        address route = routes[token];
        if (route == address(0)) revert Errors.NO_ORACLE_ROUTE(token);
        uint256 px = IBaseOracle(route).getPrice(token);
        if (px == 0) revert Errors.PRICE_FAILED(token);
        return px;
    }
```
The `IBaseOracle` retrieves the price from any of the supported oracles and returns it multiplied by 10**18

The problem is in this calculation:
```solidity

    function _getTokenValue(
        address token,
        uint256 amount
    ) internal view returns (uint256 value) {
        uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
        value = (_getPrice(token) * amount) / 10 ** decimals; //@audit wrongly divides by token decimal here
    } 
```

The problem is, if the underlying token, is a token with a different precision value, like USDT or USDC, there will be a precision loss. This is true, since the oracle returns a price multiplied by 10** 18, while a token like USDT has a 6 decimal precision, the division will return a wrong value, due to loss of precision

## Impact
Users position will be at risk of liquidation, since [getPositionRisk](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L456) will always compute with the wrong values, also the user might not be able to close or interact with any function in the BlueBerryBank contract due to this check in the execute function:
```solidity
 if (isLiquidatable(positionId)) revert Errors.INSUFFICIENT_COLLATERAL();

```
## Code Snippet
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L151
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/BlueBerryBank.sol#L456
https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/CoreOracle.sol#L151

## Tool used

Manual Review

## Recommendation
will recommend, dividing by the same precision instead
```solidity
 function _getTokenValue(
        address token,
        uint256 amount
    ) internal view returns (uint256 value) {
        uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
      -  value = (_getPrice(token) * amount) / 10 ** decimals;
      + value = (_getPrice(token) * amount) / 10 ** 18;
    }

```

**Comment by Tendency001** [comment]
Escalate for 10 USD

I believe this issue hasn't been rightly judged, it very much relates to #28 

The protocol made an assumption that all of the tokens they will be interacting with will be of 18 decimal precision, which isn't the case, if the token is of any other precision i.e 6 decimal precision, the returned USD value here will be wrong

```solidity
   uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
      -  value = (_getPrice(token) * amount) / 10 ** decimals;
```
This is true because, the Base Oracle returns prices of tokens in 18 decimal precision

Please kindly look into this

**Comment by sherlock-admin** [comment]
> Escalate for 10 USD
> 
> I believe this issue hasn't been rightly judged, it very much relates to #28 
> 
> The protocol made an assumption that all of the tokens they will be interacting with will be of 18 decimal precision, which isn't the case, if the token is of any other precision i.e 6 decimal precision, the returned USD value here will be wrong
> 
> ```solidity
>    uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
>       -  value = (_getPrice(token) * amount) / 10 ** decimals;
> ```
> This is true because, the Base Oracle returns prices of tokens in 18 decimal precision
> 
> Please kindly look into this

You've deleted an escalation for this issue.

**Comment by IAm0x52** [comment]
The current code always normalizes the `value` to 18 dp which I believe is the intention of the code.

Lets take an example with USDC, which has 6 dp. Assume the price of USDC is $1 and we are valuing 10e6 USDC. The current math would return:

10e6 * 1e18 / 1e6 = 10e18

This values our USDC at $10 with 18 dp, which I believe is the correct value.

**Comment by Tendency001** [comment]
The calculation you have mentioned above is handled by the oracles to ensure the prices are returned with 18 dp, you are missing this:

```solidity
   uint256 decimals = IERC20MetadataUpgradeable(token).decimals();
      -  value = (_getPrice(token) * amount) / 10 ** decimals;
```

The issue am discussing here, has nothing to do with how the oracles handle the precision conversion, the problem is in how `_getTokenValue` handle the conversion from the returned dp to a USD value, like you have rightly said the returned value from the oracles are in 18 dp, isn't it important that the price be divided by 18 dp in order to get the value?

dividing by the token decimal poses this problem here, when the underlying token is of 6dp, the division will not return the right value to the calling functions

**Comment by IAm0x52** [comment]
`value` needs to be in 18 dp. Amount will always be in the precision of the token. So when you multiple amount * price it will yield a value that is 18 + token decimals dp so in order to restore it to 18 dp you need to divide by the decimals of the the token.

**Comment by IAm0x52** [comment]
/// @notice Return USD price of given token, multiplied by 10**18.
  
 If the price if the asset is $1 then this will return 1e18 which means that it is 18 dp. There is no division needed, since the oracle is already returning the price to 18 dp. Assuming a token of 6 dp, when you multiply amount * price it gives you a value that is 24 dp so you have to divide by 6 dp to get it back to 18 dp

**Comment by Tendency001** [comment]
Your claim isn't true, let's use [chainLInkAdapterOrcle](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/ChainlinkAdapterOracle.sol#L77-L97) for example, 

```solidity
    function getPrice(address token_) external view override returns (uint256) {
        // remap token if possible
        address token = remappedTokens[token_];
        if (token == address(0)) token = token_;

        uint256 maxDelayTime = timeGaps[token];
        if (maxDelayTime == 0) revert Errors.NO_MAX_DELAY(token_);

        // Get token-USD price
        uint256 decimals = registry.decimals(token, USD);
        (, int256 answer, , uint256 updatedAt, ) = registry.latestRoundData( 
            token,
            USD
        );
        if (updatedAt < block.timestamp - maxDelayTime)
            revert Errors.PRICE_OUTDATED(token_);
        if (answer <= 0) revert Errors.PRICE_NEGATIVE(token_);

        return
            (answer.toUint256() * Constants.PRICE_PRECISION) / 10 ** decimals; 
    }   
```

The comment /// @notice Return USD price of given token, multiplied by 10** 18.
means the price returned from the oracle is multiplied by 10** 18

The comment in getTokenValue
    /**
     * @dev Return the USD value of the token and amount.
Notice this:

```solidity
        return
            (answer.toUint256() * Constants.PRICE_PRECISION) / 10 ** decimals;
```
Since chain link returns the price with the dp of the token, to ensure the returned price is in 18dp the answer is multiplied by 18 dp then divided by the token decimal. i.e for 6 dp tokens, 10** 6 * 10** 18 / 10** 6
This cancels out the token returned decimals and makes sure the returned price decimal is always 10**18

Please take note of the comments in [ChainlinkAdapterOracle.getPrice](https://github.com/sherlock-audit/2023-05-blueberry/blob/ec27daf841c4e89445af2559a4cc7b1f09ee2858/blueberry-core/contracts/oracle/ChainlinkAdapterOracle.sol#L77-L97) function 

```
    /**
     * @notice Returns the USD price of given token, price value has 18 decimals
     * @param token_ Token address to get price of
     * @return price USD price of token in 18 decimal
     */
```

**Comment by IAm0x52** [comment]
function _getPrice( //@audit price will be multiplied by 18 here
        address token
    ) internal view whenNotPaused returns (uint256) {
        address route = routes[token];
        if (route == address(0)) revert Errors.NO_ORACLE_ROUTE(token);
        uint256 px = IBaseOracle(route).getPrice(token);
        if (px == 0) revert Errors.PRICE_FAILED(token);
        return px;
    }

px is returned directly and is never multiplied by 1e18._getPrice returns the exact answer returned by IBaseOracle.getPrice. Since IBaseOracle.getPrice always returns to 18 dp, as it seems we both agree, then _getPrice will always return a price to 18 dp.

**Comment by Tendency001** [comment]
It is difficult to understand were I got this wrong

**Comment by Tendency001** [comment]
Can you confirm from the team please

**Comment by Tendency001** [comment]
IBaseOracle acts like the router, it returns the price from the availabe oracle

**Comment by IAm0x52** [comment]
IBaseOracle is just an interface not a specific contract. The route is the address of the oracle adapter from which you get the price.
